services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2025-latest
      container_name: closavy-sqlserver
      environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "AsdAsd99!!"
      ports:
        - "14330:1433"
      volumes:
        - test_volume2:/var/opt/mssql

volumes:
  test_volume2: